### ISSUE TITLE
Regression: 'v-else-if' directives require being preceded by the element which has a 'v-if' or 'v-else-if' directive

### ISSUE THREAD

**Issue by sid-6581** [rashfael/eslint-plugin-vue-pug#12]
After upgrading to 0.5.1 I'm getting errors on `v-else` and `v-else-if`:

![image](https://user-images.githubusercontent.com/28602336/175040472-10e95cd9-8a98-446b-8734-613eb02705a9.png)

**Comment by rashfael** [comment]
Can you try again with 0.5.2 ?
If that does not fix your problem I need a bit more of your template.

**Comment by sid-6581** [comment]
That fixed both regressions for me! Thanks!
