### ISSUE TITLE
The img tag raises a warning (vue/html-indent error)

### ISSUE THREAD

**Issue by nbarikipoulos** [rashfael/eslint-plugin-vue-pug#15]
Hi,

All is in the title: The raised error is about the closing parenthesis. 

Note that it does not happen using any other html tag, only with the 'img' tag...

```
img(
  src="./assets/logo.png"
)
``` 
```
 20:1   warning  Expected indentation of 2 spaces but found 0 spaces  vue/html-indent
```
So prepending 2 spaces to the closing parenthesis fixes it but then, code is not really nice.
```
img(
  src="./assets/logo.png"
  )
```

**Comment by rashfael** [comment]
Currently `eslint-plugin-vue-pug` only makes the existing `eslint-plugin-vue` rules work for pug templates. The upstream rules are designed for html and sometimes behave weirdly. Having dedicated rules for pug indentation is planned, but not there yet. If you don't want those kinds of warnings you get you can disable the rule `vue/html-indent` in your eslint config by addid `"vue/html-indent": 0` to your `rules` section.

**Comment by nbarikipoulos** [comment]
My mistake, I should read the README to the end...
Anyway, 'weird' is the good word: that appends only whit img at level 0, embedding it in another tag 'fixes' it, as in real life... 
```
div
  img(
    src="./assets/logo.png"
  )
```

Sorry for the noise.

**Comment by Grawl** [comment]
It's definitely not a noise and looks like a real bug if it shows error in one scenario and does not in another.

**Comment by nbarikipoulos** [comment]
If I understood well both the  author's comment and the warn in README, this feature is not implemented for pug purposes yet.

So, it sounds a bite strange to leave my issue about it (even if it seems to work properly with indent in most cases).
