### ISSUE TITLE
package.json link is broken

### ISSUE THREAD

**Issue by Shinigami92** [rashfael/eslint-plugin-vue-pug#2]
![image](https://user-images.githubusercontent.com/7195563/164394181-86a84463-7083-4560-b578-4093075d1eed.png)

package.json link is broken

**Comment by rashfael** [comment]
Hm, interesting. I can find that string only in the README.md. Looks like the thing responsible for rendering that tooltip fails at parsing markdown?
The package.json currently has no `homepage` or `repository` links, I'll fix that with the next release.

**Comment by Shinigami92** [comment]
<img width="477" alt="image" src="https://user-images.githubusercontent.com/7195563/164618761-86b2c233-00a6-4db0-abf9-98284b258a96.png">

fixed
