### ISSUE TITLE
Using typescript causes "declared but never read" errors for components/variables only used in pug template

### ISSUE THREAD

**Issue by Dylancyclone** [rashfael/eslint-plugin-vue-pug#27]
I'm working on a project with the following structure:
- Vue 3
- Vite 5
- Typescript 5
- ESLint 9 (also tried 8)

And I'm having trouble getting this plugin to work with typescript. Whenever I have my SFC with both the template using `pug` and the script using `ts`, typescript cannot find components/variables being used in the template and throws an error saying they're unused.

![image](https://github.com/rashfael/eslint-plugin-vue-pug/assets/19830705/37c5e1e3-7747-4254-b155-6734c2c4d0d2)

![image](https://github.com/rashfael/eslint-plugin-vue-pug/assets/19830705/570f26fc-254c-44cb-981c-8f899172100f)
![image](https://github.com/rashfael/eslint-plugin-vue-pug/assets/19830705/80c17d16-2530-4497-8d10-8d7db23cf9ba)

.eslint.cjs:
```js
module.exports = {
	root: true,
	// `parser: 'vue-eslint-parser'` is already included with any 'plugin:vue/**' config and should be omitted
	parserOptions: {
		parser: require.resolve("@typescript-eslint/parser"),
		extraFileExtensions: [".vue"],
	},
	env: {
		browser: true,
		es2021: true,
		node: true,
		"vue/setup-compiler-macros": true,
	},
	extends: [
		"plugin:@typescript-eslint/recommended",
		"plugin:vue/vue3-recommended", // Priority C: Recommended (Minimizing Arbitrary Choices and Cognitive Overhead)
		"plugin:vue-pug/vue3-recommended",
		"prettier",
	],

	plugins: [
		"@typescript-eslint",
		// required to lint *.vue files
		"vue",
	],
	[...]
}
```

Thank you for your awesome work on this plugin!

**Comment by rashfael** [comment]
Does that warning come from eslint itself or from somewhere else?
Do you also get that warning when you run eslint in the console?

**Comment by Dylancyclone** [comment]
Looks like it's coming from the typescript compiler, not eslint. 

I found a few issues describing the same thing https://github.com/vuejs/eslint-plugin-vue/issues/1810 and https://github.com/vuejs/language-tools/issues/604, both of which recommended using this package https://github.com/Shinigami92/eslint-plugin-vue-pug-sfc. But that has since been archived in favor of this package. 
Before migrating this project to typescript, this plugin was successfully handling all the rules (thanks again), so the only difference appears to be typescript

**Comment by rashfael** [comment]
Sadly eslint-plugin-vue-pug can only provide pug support to eslint rules. Eslint can include a typescript pass and there is [@vue/eslint-config-typescript](https://www.npmjs.com/package/@vue/eslint-config-typescript) which helps setting up typescript inside eslint.

eslint-plugin-vue-pug can't teach other typescript (editor) tools how to parse pug though. The direct ts integration in vscode for example isn't aware of pug, leading to the issue you describe.

There is https://www.npmjs.com/package/@vue/language-plugin-pug. I haven't tried that out myself though.

**Comment by Dylancyclone** [comment]
At a first glance, it looks like `@vue/language-plugin-pug` is doing the trick! Thank you very much!

**Comment by yanzhangshuai** [comment]
> 可悲的是，eslint-plugin-vue-pug 只能为 eslint 规则提供 pug 支持。Eslint 可以包含打字稿传递，并且有 [@vue/eslint-config-typescript](https://www.npmjs.com/package/@vue/eslint-config-typescript)，它有助于在 eslint 中设置打字稿。
> 
> eslint-plugin-vue-pug 无法教其他 TypeScript（编辑器）工具如何解析 Pug。例如，vscode 中的直接 ts 集成不知道 pug，从而导致您描述的问题。
> 
> 有 https://www.npmjs.com/package/@vue/language-plugin-pug。不过，我自己还没有尝试过。



> Sadly eslint-plugin-vue-pug can only provide pug support to eslint rules. Eslint can include a typescript pass and there is [@vue/eslint-config-typescript](https://www.npmjs.com/package/@vue/eslint-config-typescript) which helps setting up typescript inside eslint.
> 
> eslint-plugin-vue-pug can't teach other typescript (editor) tools how to parse pug though. The direct ts integration in vscode for example isn't aware of pug, leading to the issue you describe.
> 
> There is https://www.npmjs.com/package/@vue/language-plugin-pug. I haven't tried that out myself though.



> At a first glance, it looks like `@vue/language-plugin-pug` is doing the trick! Thank you very much!



@vue/language-plugin-pug  is right, thanks。But I had another problem。 
 eslint --fix  remove no-unused-imports。 But  Will remove used component。 
Can Help me? thinks。 


![QQ_1722067531321](https://github.com/user-attachments/assets/4fd2e1ef-32d9-4965-941b-0303905a12a2)


This is my configuration
![QQ_1722067884294](https://github.com/user-attachments/assets/47ba02f6-07e8-41e0-9f40-fc40328b5955)

**Comment by yanzhangshuai** [comment]
> Sadly eslint-plugin-vue-pug can only provide pug support to eslint rules. Eslint can include a typescript pass and there is [@vue/eslint-config-typescript](https://www.npmjs.com/package/@vue/eslint-config-typescript) which helps setting up typescript inside eslint.
> 
> eslint-plugin-vue-pug can't teach other typescript (editor) tools how to parse pug though. The direct ts integration in vscode for example isn't aware of pug, leading to the issue you describe.
> 
> There is https://www.npmjs.com/package/@vue/language-plugin-pug. I haven't tried that out myself though.



> At a first glance, it looks like `@vue/language-plugin-pug` is doing the trick! Thank you very much!


@vue/language-plugin-pug is right. thinks. But I have another question
eslint --fix will remove no-unused-imports，Will mistakenly remove used。 
Can Help me? thinks。 


![QQ_1722067531321](https://github.com/user-attachments/assets/4fd2e1ef-32d9-4965-941b-0303905a12a2)


This is my configuration
![QQ_1722067884294](https://github.com/user-attachments/assets/47ba02f6-07e8-41e0-9f40-fc40328b5955)

**Comment by rashfael** [comment]
Please create a separate issue for this new problem, with a clean reproduction if possible.

**Comment by simonmaass** [comment]
@Dylancyclone would you help me on how to include @vue/language-plugin-pug to eslint flat config - thank you!

**Comment by Dylancyclone** [comment]
@simonmaass You should be able to just follow these instructions: https://www.npmjs.com/package/@vue/language-plugin-pug
