### ISSUE TITLE
Does it work with  "plugin:vue/recommended"

### ISSUE THREAD

**Issue by achinchen** [rashfael/eslint-plugin-vue-pug#5]
## Description

As title, I tried to use the plugin in the Vue2 project, but it seems not work for me. 
My question is does it suppose to work with "plugin:vue/recommended" or not? 😅

However, the project is great one. 👍 

### relevant dependency
```
    "eslint-plugin-vue": "^8.7.1",
    "eslint-plugin-vue-pug": "^0.4.2",
    "vue-eslint-parser": "^9.0.0-alpha.0"
```

### .eslintconfig.js
````
module.exports = {
  parserOptions: {
      parser: '@babel/eslint-parser',
      templateTokenizer: { pug: 'vue-eslint-parser-template-tokenizer-pug' }
    },
    extends: [
      'eslint:recommended',
      'plugin:vue/recommended',
      'plugin:vue-pug/recommended',
      'eslint-config-prettier'
    ]
  }

**Comment by Shinigami92** [comment]
You forcefully need to install "vue-eslint-parser": "~9.0.0-alpha.0"

**Comment by achinchen** [comment]
Close the issue by reload several times VS Code and suddenly works `lol`
The above config in this issue description should work and it does work.
